<?php
/**
 * Created automatically by salesforce-sdk.
 */

namespace CNSDose\Salesforce\Models\Metadata;

use MyCLabs\Enum\Enum;

class UserDateInterval extends Enum
{
    const INTERVAL_CURRENT = 'INTERVAL_CURRENT';
    const INTERVAL_CURNEXT1 = 'INTERVAL_CURNEXT1';
    const INTERVAL_CURPREV1 = 'INTERVAL_CURPREV1';
    const INTERVAL_NEXT1 = 'INTERVAL_NEXT1';
    const INTERVAL_PREV1 = 'INTERVAL_PREV1';
    const INTERVAL_CURNEXT3 = 'INTERVAL_CURNEXT3';
    const INTERVAL_CURFY = 'INTERVAL_CURFY';
    const INTERVAL_PREVFY = 'INTERVAL_PREVFY';
    const INTERVAL_PREV2_FY = 'INTERVAL_PREV2FY';
    const INTERVAL_AGO2_FY = 'INTERVAL_AGO2FY';
    const INTERVAL_NEXTFY = 'INTERVAL_NEXTFY';
    const INTERVAL_PREVCURFY = 'INTERVAL_PREVCURFY';
    const INTERVAL_PREVCUR2_FY = 'INTERVAL_PREVCUR2FY';
    const INTERVAL_CURNEXTFY = 'INTERVAL_CURNEXTFY';
    const INTERVAL_CUSTOM = 'INTERVAL_CUSTOM';
    const INTERVAL_YESTERDAY = 'INTERVAL_YESTERDAY';
    const INTERVAL_TODAY = 'INTERVAL_TODAY';
    const INTERVAL_TOMORROW = 'INTERVAL_TOMORROW';
    const INTERVAL_LASTWEEK = 'INTERVAL_LASTWEEK';
    const INTERVAL_THISWEEK = 'INTERVAL_THISWEEK';
    const INTERVAL_NEXTWEEK = 'INTERVAL_NEXTWEEK';
    const INTERVAL_LASTMONTH = 'INTERVAL_LASTMONTH';
    const INTERVAL_THISMONTH = 'INTERVAL_THISMONTH';
    const INTERVAL_NEXTMONTH = 'INTERVAL_NEXTMONTH';
    const INTERVAL_LASTTHISMONTH = 'INTERVAL_LASTTHISMONTH';
    const INTERVAL_THISNEXTMONTH = 'INTERVAL_THISNEXTMONTH';
    const INTERVAL_CURRENTQ = 'INTERVAL_CURRENTQ';
    const INTERVAL_CURNEXTQ = 'INTERVAL_CURNEXTQ';
    const INTERVAL_CURPREVQ = 'INTERVAL_CURPREVQ';
    const INTERVAL_NEXTQ = 'INTERVAL_NEXTQ';
    const INTERVAL_PREVQ = 'INTERVAL_PREVQ';
    const INTERVAL_CURNEXT3_Q = 'INTERVAL_CURNEXT3Q';
    const INTERVAL_CURY = 'INTERVAL_CURY';
    const INTERVAL_PREVY = 'INTERVAL_PREVY';
    const INTERVAL_PREV2_Y = 'INTERVAL_PREV2Y';
    const INTERVAL_AGO2_Y = 'INTERVAL_AGO2Y';
    const INTERVAL_NEXTY = 'INTERVAL_NEXTY';
    const INTERVAL_PREVCURY = 'INTERVAL_PREVCURY';
    const INTERVAL_PREVCUR2_Y = 'INTERVAL_PREVCUR2Y';
    const INTERVAL_CURNEXTY = 'INTERVAL_CURNEXTY';
    const INTERVAL_LAST7 = 'INTERVAL_LAST7';
    const INTERVAL_LAST30 = 'INTERVAL_LAST30';
    const INTERVAL_LAST60 = 'INTERVAL_LAST60';
    const INTERVAL_LAST90 = 'INTERVAL_LAST90';
    const INTERVAL_LAST120 = 'INTERVAL_LAST120';
    const INTERVAL_NEXT7 = 'INTERVAL_NEXT7';
    const INTERVAL_NEXT30 = 'INTERVAL_NEXT30';
    const INTERVAL_NEXT60 = 'INTERVAL_NEXT60';
    const INTERVAL_NEXT90 = 'INTERVAL_NEXT90';
    const INTERVAL_NEXT120 = 'INTERVAL_NEXT120';
    const LAST_FISCALWEEK = 'LAST_FISCALWEEK';
    const THIS_FISCALWEEK = 'THIS_FISCALWEEK';
    const NEXT_FISCALWEEK = 'NEXT_FISCALWEEK';
    const LAST_FISCALPERIOD = 'LAST_FISCALPERIOD';
    const THIS_FISCALPERIOD = 'THIS_FISCALPERIOD';
    const NEXT_FISCALPERIOD = 'NEXT_FISCALPERIOD';
    const LASTTHIS_FISCALPERIOD = 'LASTTHIS_FISCALPERIOD';
    const THISNEXT_FISCALPERIOD = 'THISNEXT_FISCALPERIOD';
    const CURRENT_ENTITLEMENT_PERIOD = 'CURRENT_ENTITLEMENT_PERIOD';
    const PREVIOUS_ENTITLEMENT_PERIOD = 'PREVIOUS_ENTITLEMENT_PERIOD';
    const PREVIOUS_TWO_ENTITLEMENT_PERIODS = 'PREVIOUS_TWO_ENTITLEMENT_PERIODS';
    const TWO_ENTITLEMENT_PERIODS_AGO = 'TWO_ENTITLEMENT_PERIODS_AGO';
    const CURRENT_AND_PREVIOUS_ENTITLEMENT_PERIOD = 'CURRENT_AND_PREVIOUS_ENTITLEMENT_PERIOD';
    const CURRENT_AND_PREVIOUS_TWO_ENTITLEMENT_PERIODS = 'CURRENT_AND_PREVIOUS_TWO_ENTITLEMENT_PERIODS';
}
